# Screen Constants 
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_BACKGROUND_COLOR = (0, 0, 0)


# Asteriod Constants
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS


# Player Constants
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_COLOR = "White"